### ISSUE TITLE
OpenProject 8.0 support

### ISSUE THREAD

**Issue by jadoro** [finnlabs/openproject-themes-dark#20]
Are there any plans to support OpenProject 8.0? As far as I can see, no `stable/8` branch exists (yet?).

**Comment by ulferts** [comment]
Actually no, this plugin as a whole is no longer supported (I'll try to update the plugin to reflect that situation). The functionality can now be achieved by [the custom theming functionality build into OP](https://www.openproject.org/de/custom-themes-and-logo/)
